name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deployment to Hugging Face
        env:
          HF: ${{ secrets.HF2 }}
        run: make deploy HF=$HF