name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format code
        run: |
          pip install black
          black *.py

      - name: Lint code
        run: |
          pip install pylint
          pylint --disable=R,C *.py

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          python -m pytest tests/ -vv --cov=.

      - name: Update branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.email "$EMAIL"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update with CI results" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          repository: "roy2392/every-right-rag-solution"